parameters:
#    kenny_gbbm.example.class: Kenny\GbbmBundle\Example

services:
#    kenny_gbbm.example:
#        class: %kenny_gbbm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
pairing_service:
  class: Kenny\KennyGbbmBundle\Service\Pairing
  arguments:
      - "@service_container"